### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by acushlakoncept** [OkiemuteGold/Sample-College-Template1#2]
As an aspiring developer, it's a good practice to imbibe good HTML practices.
Let the HTML validator site: https://validator.w3.org/#validate-by-upload be always there by your side to use in validating all you HTML semantics to be sure you are on track.

Your code currently contains 17 HTML errors.

Use the HTML validator to fix the errors.

Happy Coding 👍

**Comment by OkiemuteGold** [comment]
All errors related to the use of <a> with h1, and button; as well as position of <input> fixed.
